export const FADE_TEXT_RATE = 1 / 60.0; // fades alpha by this amount each frame
export const DAMAGE_FONT_SIZE = 25;
export const DAMAGE_FONT = "Consolas";
export const DAMAGE_RECEIVED_COLOR = "#dc143c"; // crimson
export const DAMAGE_BLOCKED_COLOR = "#bec2cb"; // grey
export const DAMAGE_X_OFFSET_PX = 20; // offsets from the center of the 
export const DAMAGE_Y_OFFSET_PX = 0;  //   sprite in px
export const DEFAULT_FONT_SIZE = 12;
export const DEFAULT_FONT = "Consolas";
export const DEFAULT_FONT_COLOR = "#000000"; // black
export const TILEWIDTH = 64;
export const TILEHEIGHT = 64;
export const NUM_ENEMIES = 3;
export const VIEWPORT_WIDTH = TILEWIDTH * 22;
export const VIEWPORT_HEIGHT = TILEHEIGHT * 12;
export const TURNS_REMAINING_FONT_SIZE_STRING = "40px";
export const TURNS_REMAINING_FONT_FAMILY = "source serif pro";
export const TURNS_REMAINING_TEXT = "TURNS REMAINING:";
export const CONNECT_PROMPT_TEXT = "please play offline (click the X to the left), or connect a wallet\nand avatar by clicking on the glowing button above to continue!";
export const BLOCK_CONFIRMS = 5;
export const GAME_COST_ETHER = 0.001;
export const MINT_COST_ETHER = 0.001;